import Header from './Header/Header';
import HeroSection from './HeroSection/HeroSection';
import FlagCanvas from './Flag/Flag';
import Policy from './Policy/Policy';
import Welcome from './Welcome/Welcome';
import Campaigns from './Campaigns/Campaigns';
import Media from './Media/Media';
import Newsletter from './Newsletter/Newsletter';
import Footer from './Footer/Footer'
import Copyright from './Copyright/Copyright';
import News from './News/News'
export {Header,HeroSection,FlagCanvas, Policy, Welcome,Campaigns,Newsletter,Footer,Copyright,News,Media}